# Build the model3 DrugCount APK.
#
#   .\build.ps1              # debug build -> android\dist\DrugCount.apk
#   .\build.ps1 -Release     # same code, release build type (still debug-signed)
#   .\build.ps1 -Install     # build, then push it to the attached phone
#
# There is no keystore here, so both build types are signed with the debug key. That is
# fine for sideloading onto a test handset and not fine for a ward: a debug-signed APK
# cannot be updated in place by a release-signed one, or the other way round.

# No [CmdletBinding()] on purpose. It brings in PowerShell's common parameters, one of
# which is -Debug, and the script's own switches would collide with them.
param(
    [switch]$Release,
    [switch]$Install
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$AndroidDir = $PSScriptRoot
$RepoDir    = Split-Path $AndroidDir -Parent
$DistDir    = Join-Path $AndroidDir "dist"

$GradleVersion = "8.7"
$GradleUrl     = "https://services.gradle.org/distributions/gradle-$GradleVersion-bin.zip"

function Step($msg) { Write-Host ""; Write-Host "==> $msg" -ForegroundColor Cyan }
function Fail($msg) { throw $msg }

# ---------------------------------------------------------------- prerequisites

Step "Checking prerequisites"

if (-not $env:JAVA_HOME -and -not (Get-Command java -ErrorAction SilentlyContinue)) {
    Fail "No JDK found. Install JDK 17 and set JAVA_HOME."
}
Write-Host "  java       ok"

# Chaquopy runs pip with a local interpreter of the version it targets. app\build.gradle
# points at the project's own .venv, so the only thing to check is that it exists.
$venvPython = Join-Path $RepoDir ".venv\Scripts\python.exe"
if (-not (Test-Path $venvPython)) {
    Fail @"
No virtualenv at $venvPython

Chaquopy needs a local Python 3.10 to resolve numpy and OpenCV for the phone, and the
project's own venv is the one it is pointed at. Create it:

  python -m venv .venv
  .venv\Scripts\python.exe -m pip install -r requirements.txt
"@
}
$pyVersion = (& $venvPython --version) -replace '^Python\s+', ''
if ($pyVersion -notmatch '^3\.10\.') {
    Fail @"
$venvPython is $pyVersion, and Chaquopy needs 3.10 here.

Not a preference: Chaquopy's package repository publishes native OpenCV builds for
cp310 only, and buildPython must match the version being targeted.
"@
}
Write-Host "  buildPython $pyVersion"

$sdkRoot = $env:ANDROID_SDK_ROOT
if (-not $sdkRoot) { $sdkRoot = $env:ANDROID_HOME }
if (-not $sdkRoot) { $sdkRoot = Join-Path $env:LOCALAPPDATA "Android\Sdk" }
if (-not (Test-Path (Join-Path $sdkRoot "platforms"))) {
    Fail @"
No Android SDK at $sdkRoot

Set ANDROID_SDK_ROOT, or install the command-line tools and then:
  sdkmanager --install "platforms;android-34" "build-tools;34.0.0" "platform-tools"
"@
}
Write-Host "  sdk        $sdkRoot"

$localProps = Join-Path $AndroidDir "local.properties"
if (-not (Test-Path $localProps)) {
    # Forward slashes on purpose: this is a Java .properties file, where \U and \A are
    # not valid escapes and the backslash is silently dropped, turning C:\Users\... into
    # C:Users... The Android plugin then reports "The filename, directory name, or volume
    # label syntax is incorrect", which points nowhere near the actual problem.
    $sdkForProps = $sdkRoot -replace '\\', '/'
    @"
# Generated by build.ps1. Machine-specific; not committed.
sdk.dir=$sdkForProps
"@ | Set-Content -Path $localProps -Encoding ASCII
    Write-Host "  wrote local.properties"
}

# Gradle, vendored rather than assumed. The sibling project keeps a copy; reuse it if it
# is there, otherwise fetch one next to this script.
# RepoDir here is model3\, one deeper than model1\android's copy of this script,
# so the sibling checkout with the vendored Gradle is two levels up rather than one.
$gradleHome = Join-Path $RepoDir "..\..\pill-counter-lite\packaging\vendor\gradle-$GradleVersion"
if (-not (Test-Path (Join-Path $gradleHome "bin\gradle.bat"))) {
    $vendor = Join-Path $AndroidDir "vendor"
    $gradleHome = Join-Path $vendor "gradle-$GradleVersion"
    if (-not (Test-Path (Join-Path $gradleHome "bin\gradle.bat"))) {
        Step "Downloading Gradle $GradleVersion"
        New-Item -ItemType Directory -Force -Path $vendor | Out-Null
        $zip = Join-Path $vendor "gradle-$GradleVersion-bin.zip"
        if (-not (Test-Path $zip)) { Invoke-WebRequest -Uri $GradleUrl -OutFile $zip }
        Expand-Archive -Path $zip -DestinationPath $vendor -Force
    }
}
$gradleBin = Join-Path $gradleHome "bin\gradle.bat"

# The JVM hands -javaagent and -cp paths to the OS through the ANSI code page, not UTF-8,
# so a Gradle living under a non-ASCII directory dies before it starts:
#
#   Error opening zip file or JAR manifest missing : D:\?????\...\gradle-...-agent.jar
#   agent library failed to init: instrument
#
# Nothing in that message names the directory. A junction costs no disk, points at the
# same files, and gradle.bat's %~f keeps the junction's own ASCII path.
if ($gradleHome -notmatch '^[ -~]+$') {
    $aliasHome = Join-Path $env:LOCALAPPDATA "PillSortBuild\gradle-$GradleVersion"
    if (-not (Test-Path $aliasHome)) {
        New-Item -ItemType Directory -Force -Path (Split-Path $aliasHome -Parent) | Out-Null
        New-Item -ItemType Junction -Path $aliasHome -Target $gradleHome | Out-Null
    }
    $gradleBin = Join-Path $aliasHome "bin\gradle.bat"
    Write-Host "  gradle via $aliasHome (ASCII junction)"
}
Write-Host "  gradle     $gradleHome"

# ---------------------------------------------------------------- build

$buildType = if ($Release) { "release" } else { "debug" }
$task = if ($Release) { ":app:assembleRelease" } else { ":app:assembleDebug" }
Step "Running $task"

Push-Location $AndroidDir
try {
    & $gradleBin --no-daemon $task
    if ($LASTEXITCODE -ne 0) {
        $crash = Get-ChildItem $AndroidDir -Filter "hs_err_pid*.log" -ErrorAction SilentlyContinue |
                 Select-Object -First 1
        if ($crash) {
            Fail @"
Gradle aborted and left $($crash.Name).

That is the JVM running out of memory, not a code error, and the message Gradle prints
("daemon disappeared unexpectedly") does not say so. On Windows the binding limit is the
system commit charge rather than free RAM -- compare '\Memory\Committed Bytes' against
'\Memory\Commit Limit' in Get-Counter. Close the IDE and browser, or enlarge the page
file, and run this again.
"@
        }
        Fail "Gradle build failed"
    }
}
finally {
    Pop-Location
}

# ---------------------------------------------------------------- collect

$apk = Get-ChildItem (Join-Path $AndroidDir "app\build\outputs\apk\$buildType") -Filter "*.apk" |
       Select-Object -First 1
if (-not $apk) { Fail "Build reported success but produced no APK" }

New-Item -ItemType Directory -Force -Path $DistDir | Out-Null
$target = Join-Path $DistDir "DrugCount.apk"
Copy-Item $apk.FullName $target -Force

Write-Host ""
Write-Host "APK:  $target" -ForegroundColor Green
Write-Host "Size: $([math]::Round((Get-Item $target).Length / 1MB, 1)) MB"

# ---------------------------------------------------------------- install

if ($Install) {
    $adb = Join-Path $sdkRoot "platform-tools\adb.exe"
    if (-not (Test-Path $adb)) { Fail "No adb at $adb" }
    Step "Installing"
    # -r replaces an existing copy, -d allows a downgrade. Both matter while iterating:
    # without them a reinstall of the same versionCode is refused outright.
    & $adb install -r -d $target
    if ($LASTEXITCODE -ne 0) { Fail "adb install failed" }
    Write-Host ""
    Write-Host "Watch it start up with:" -ForegroundColor Yellow
    Write-Host "  adb logcat -s pillsort:* python.std:* AndroidRuntime:E"
}
